### ISSUE TITLE
Formatter rules enforcing

### ISSUE THREAD

**Issue by knyfi** [TerosTechnology/vscode-terosHDL#619]
Formatter using VSG does not enforce prefix and suffix rules :

**To Reproduce**

rule file contains :
```
rule:
  constant_015:
    disable: false
    prefixes: ['CST_']
```
vhdl file contains : 
`constant FAULTY_CONSTANT: std_logic_vector(7 downto 0)  := x"AA";`

**Observation:**
The formatter does not add prefix to constant.

**Please complete the following information:**
 - OS: WIN10
 - VSCode version 1.89.1
